server:
  # port: 3000
  port: 8080

db:
  synchronize: true
  type: 'postgres'
  host: 'macro-database.cepvscxgqsjs.ap-northeast-2.rds.amazonaws.com'
  port: 5432
  username: 'root'
  password: 'yeongmin'
  database: 'macroDatabase'

jwt:
  secret: 'topSecret51'
